name: Build and Release Artifact

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build Plugin
        run: ./gradlew buildPlugin --info

      # Upload plugin artifact to make it available in the next jobs
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bettermarkdown-plugin
          path: ./build/distributions/*.zip
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: bettermarkdown-plugin
          path: build
      - name: Set Release Tag
        id: set_release_tag
        run: echo "::set-output name=release_tag::v$(git log --pretty=format:'%h' -n 1)"
      - name: Upload Release Asset
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: true
          tag_name: ${{ steps.set_release_tag.outputs.release_tag }}
          files: |
            build/*.zip