name: Build and Release Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: mkdir -p build/artifact

      - run: ./gradlew buildPlugin --info
      - uses: actions/upload-artifact@v3
        with:
          name: bettermarkdown
          path: build/artifact/bettermarkdown.jar